
import React, { useState, useEffect, useRef } from 'react';
import { 
  BookOpen, Sparkles, Sigma, Zap, ArrowLeft, Clock, Share2, Maximize2, 
  Infinity, RefreshCw, Compass, Trophy, Brain, Layers, Waves, Target, 
  Binary as BinaryIcon, ShieldAlert, Puzzle, Scale, History, ShieldCheck, 
  Search, Database, List, Microscope, TrendingUp, Wind, Droplets, 
  ChevronLeft, ChevronRight, Atom, Shield, Variable, FunctionSquare,
  Grid3X3, Shapes, GitMerge, Calculator, Network, Box, Lock, ArrowUpRight,
  Hash, ArrowRight, CheckCircle2
} from 'lucide-react';

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: React.ReactNode;
  icon: React.ReactNode;
  color: string;
  readTime: string;
  date: string;
  tags: string[];
}

const blogPosts: BlogPost[] = [
  {
    id: "fractals",
    title: "Fractals: The Hidden Geometry of Nature",
    excerpt: "Exploring the Mandelbrot set and how infinite complexity arises from simple recursive equations.",
    icon: <Sparkles className="w-8 h-8" />,
    color: "from-purple-600 to-indigo-600",
    readTime: "12 min",
    date: "March 15, 2024",
    tags: ["Geometry", "Recursion", "Chaos Theory"],
    content: (
      <div className="space-y-12 text-slate-300 font-light">
        {/* Introduction */}
        <section className="space-y-6">
          <p className="text-xl md:text-2xl leading-relaxed text-slate-200 font-normal">
            Clouds are not spheres, mountains are not cones, coastlines are not circles, and bark is not smooth, nor does lightning travel in a straight line.
          </p>
          <p className="leading-relaxed">
            For centuries, classical Euclidean geometry—the world of smooth lines and perfect shapes—was our primary tool for describing the universe. But the natural world is rough, jagged, and chaotic. In 1975, mathematician <strong>Benoît Mandelbrot</strong> introduced a new term to describe these irregular shapes: <span className="text-indigo-400 font-medium">Fractals</span>.
          </p>
        </section>

        {/* Section 1: Self-Similarity */}
        <section className="relative overflow-hidden rounded-3xl bg-slate-900/40 border border-slate-800 p-8 md:p-10 space-y-6">
          <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>
          
          <div className="flex items-center gap-4 mb-2">
             <div className="p-3 rounded-xl bg-indigo-500/10 text-indigo-400">
               <Infinity size={24} />
             </div>
             <h3 className="text-2xl font-bold text-white">Infinite Regression</h3>
          </div>
          
          <p>
            The defining characteristic of a fractal is <strong>self-similarity</strong>. This means the object looks roughly the same at any scale. Zoom into a coastline, and the jagged bays and inlets resemble the shape of the entire continent. Zoom into a fern leaf, and each leaflet looks like a miniature version of the whole frond.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
             {[
               { title: "Macro Scale", desc: "The jagged outline of the British coastline.", color: "border-indigo-500/30 text-indigo-400" },
               { title: "Meso Scale", desc: "The branching patterns of river deltas.", color: "border-purple-500/30 text-purple-400" },
               { title: "Micro Scale", desc: "The bronchioles within human lungs.", color: "border-emerald-500/30 text-emerald-400" }
             ].map((item, i) => (
               <div key={i} className={`p-5 rounded-2xl bg-slate-950/50 border ${item.color} backdrop-blur-sm`}>
                  <div className={`text-sm font-bold uppercase tracking-wider mb-2 ${item.color.split(' ')[1]}`}>{item.title}</div>
                  <div className="text-slate-400 text-sm leading-relaxed">{item.desc}</div>
               </div>
             ))}
          </div>
        </section>

        {/* Section 2: The Mandelbrot Set */}
        <section className="space-y-8">
           <div className="flex items-center gap-4">
             <div className="h-px flex-1 bg-slate-800"></div>
             <h3 className="text-3xl font-bold text-white text-center">The God Equation</h3>
             <div className="h-px flex-1 bg-slate-800"></div>
           </div>

           <p>
             The most famous fractal, the <strong>Mandelbrot Set</strong>, is generated by a deceptively simple iterative equation calculated in the complex plane.
           </p>

           <div className="my-8 relative group cursor-default">
              <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 rounded-2xl blur opacity-20 group-hover:opacity-40 transition duration-1000"></div>
              <div className="relative bg-slate-950 border border-slate-800 rounded-2xl p-10 flex flex-col items-center justify-center gap-6">
                 <div className="text-5xl md:text-7xl font-serif text-transparent bg-clip-text bg-gradient-to-br from-white via-indigo-100 to-indigo-400">
                    {'z_{n+1} = z_n^2 + c'}
                 </div>
                 <div className="flex gap-8 text-sm md:text-base text-slate-500 font-mono">
                    <span className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-indigo-500"></span> z = variable</span>
                    <span className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-purple-500"></span> c = constant</span>
                 </div>
              </div>
           </div>

           <div className="space-y-4">
              <h4 className="text-xl font-bold text-white">How it works:</h4>
              <ol className="list-decimal list-inside space-y-4 text-slate-400 ml-4 marker:text-indigo-500 marker:font-bold">
                 <li>Start with <code className="text-indigo-300 bg-indigo-500/10 px-1.5 py-0.5 rounded font-mono text-sm">z = 0</code>.</li>
                 <li>Choose a point <code className="text-purple-300 bg-purple-500/10 px-1.5 py-0.5 rounded font-mono text-sm">c</code> in the complex plane (e.g., -0.5 + 0.5i).</li>
                 <li>Plug them into the equation to get a new <code className="text-indigo-300 bg-indigo-500/10 px-1.5 py-0.5 rounded font-mono text-sm">z</code>.</li>
                 <li>Take that new <code className="text-indigo-300 bg-indigo-500/10 px-1.5 py-0.5 rounded font-mono text-sm">z</code>, square it, and add <code className="text-purple-300 bg-purple-500/10 px-1.5 py-0.5 rounded font-mono text-sm">c</code> again.</li>
                 <li>Repeat infinitely.</li>
              </ol>
              <div className="p-6 bg-slate-900/50 border-l-2 border-emerald-500 text-slate-400 italic">
                 If the value of <strong>z</strong> remains bounded (it doesn't shoot off to infinity) forever, then the point <strong>c</strong> is inside the Mandelbrot Set. If it escapes to infinity, it's outside.
              </div>
           </div>
        </section>

        {/* Visual Graph: Complex Plane */}
        <section className="space-y-6">
            <h3 className="text-2xl font-bold text-white">Visualizing the Trap</h3>
            <p>
                Think of the Mandelbrot set as a "trap" on the complex number plane. We pick a coordinate, treating it as a number <em>c</em>. We then apply the rule <code>z² + c</code> repeatedly.
            </p>
            
            <div className="relative w-full aspect-[16/9] md:aspect-[2/1] bg-slate-900 rounded-2xl border border-slate-800 overflow-hidden flex items-center justify-center group select-none">
                {/* Grid Background */}
                <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:20px_20px]"></div>
                
                {/* Axes */}
                <div className="absolute w-full h-px bg-slate-700"></div>
                <div className="absolute h-full w-px bg-slate-700"></div>

                {/* The Circle of Radius 2 */}
                <div className="absolute w-[250px] h-[250px] rounded-full border-2 border-dashed border-rose-500/30"></div>
                <div className="absolute text-rose-500/50 text-xs font-mono translate-x-[90px] -translate-y-[140px]">Escape Radius (|z| &gt; 2)</div>

                {/* Animated Orbit Path for a Stable Point (Inside Set) */}
                <div className="absolute">
                    <svg width="300" height="300" viewBox="-150 -150 300 300" className="overflow-visible">
                         <circle cx="-50" cy="20" r="3" fill="#10b981" className="animate-pulse" /> {/* Start */}
                         <text x="-50" y="40" fill="#10b981" fontSize="10" textAnchor="middle" fontWeight="bold">Stable c</text>
                         <path d="M-50,20 Q-20,-40 -10,10 T-30,0" fill="none" stroke="#10b981" strokeWidth="1.5" className="opacity-60" />
                    </svg>
                </div>

                {/* Animated Orbit Path for an Unstable Point (Outside Set) */}
                <div className="absolute">
                    <svg width="300" height="300" viewBox="-150 -150 300 300" className="overflow-visible">
                         <circle cx="60" cy="-60" r="3" fill="#ef4444" className="animate-pulse" /> {/* Start */}
                         <text x="60" y="-80" fill="#ef4444" fontSize="10" textAnchor="middle" fontWeight="bold">Unstable c</text>
                         {/* Path escaping the circle */}
                         <path d="M60,-60 Q80,-20 100,-80 T160,-160" fill="none" stroke="#ef4444" strokeWidth="1.5" strokeDasharray="4,4" className="opacity-60" />
                    </svg>
                </div>

                <div className="absolute bottom-4 right-4 text-slate-500 text-xs font-mono bg-slate-950/80 px-2 py-1 rounded border border-slate-800">
                    Complex Plane (Argand Diagram)
                </div>
            </div>

             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                 <div className="p-4 rounded-xl bg-emerald-900/10 border border-emerald-500/20">
                     <div className="text-emerald-400 font-bold mb-1 text-sm flex items-center gap-2"><CheckCircle2 size={14}/> Bounded (In the Set)</div>
                     <div className="text-slate-400 text-xs">The orbit dances around the origin forever, never escaping the circle of radius 2. These points are painted black.</div>
                 </div>
                 <div className="p-4 rounded-xl bg-rose-900/10 border border-rose-500/20">
                     <div className="text-rose-400 font-bold mb-1 text-sm flex items-center gap-2"><ShieldAlert size={14}/> Unbounded (Out of Set)</div>
                     <div className="text-slate-400 text-xs">The orbit spirals outwards, growing larger with each step until it escapes to infinity. We color these based on how fast they escape.</div>
                 </div>
             </div>
        </section>

        {/* Section 3: The Code */}
        <section className="space-y-6">
          <h3 className="text-2xl font-bold text-white flex items-center gap-3">
             <BinaryIcon className="text-indigo-500" />
             The Algorithm
          </h3>
          <p>
            Implementing the Mandelbrot set in code is surprisingly straightforward. We map pixels on the screen to coordinates in the complex plane and iterate.
          </p>

          <div className="mockup-code bg-slate-950 border border-slate-800 rounded-2xl overflow-hidden text-sm md:text-base shadow-xl">
            <div className="flex items-center gap-2 px-4 py-3 bg-slate-900 border-b border-slate-800">
               <div className="w-3 h-3 rounded-full bg-red-500"></div>
               <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
               <div className="w-3 h-3 rounded-full bg-green-500"></div>
               <span className="ml-2 font-mono text-xs text-slate-500">fractal_generator.js</span>
            </div>
            <pre className="p-6 overflow-x-auto text-slate-300 font-mono leading-relaxed">
{`function isInMandelbrotSet(c_re, c_im, max_iter) {
  let z_re = 0, z_im = 0;
  
  for (let i = 0; i < max_iter; i++) {
    // z^2 = (a+bi)^2 = a^2 - b^2 + 2abi
    let z_re_new = (z_re * z_re) - (z_im * z_im) + c_re;
    let z_im_new = (2 * z_re * z_im) + c_im;
    
    z_re = z_re_new;
    z_im = z_im_new;
    
    // Check if magnitude > 2 (escape radius)
    if (z_re*z_re + z_im*z_im > 4) return i; // Escaped
  }
  
  return max_iter; // Bounded
}`}
            </pre>
          </div>
        </section>

        {/* Conclusion */}
        <section className="pt-8 border-t border-slate-800">
           <p className="text-lg text-slate-400 italic text-center max-w-2xl mx-auto">
             "Bottomless wonders spring from simple rules which are repeated without end."
             <br />
             <span className="text-indigo-400 not-italic font-bold mt-2 block">— Benoît Mandelbrot</span>
           </p>
        </section>
      </div>
    )
  },
  {
    id: "millennium",
    title: "The 7 Millennium Prize Problems",
    excerpt: "A deep dive into the unsolved mysteries that define modern mathematics and carry a $1,000,000 reward.",
    icon: <Sigma className="w-8 h-8" />,
    color: "from-emerald-600 to-teal-600",
    readTime: "35 min",
    date: "Feb 28, 2024",
    tags: ["Millennium Prize", "Complexity", "Physics"],
    content: (
      <div className="space-y-16 text-slate-300 font-light">
        {/* Intro */}
        <section className="space-y-6">
          <p className="text-xl md:text-2xl leading-relaxed text-slate-200 font-normal">
            On May 24, 2000, the Clay Mathematics Institute (CMI) in Cambridge, Massachusetts, established seven "Millennium Prize Problems."
          </p>
          <div className="p-6 rounded-2xl bg-gradient-to-r from-emerald-900/20 to-teal-900/20 border border-emerald-500/20 flex items-center gap-6">
             <div className="text-4xl font-bold text-emerald-400 font-serif italic">$1,000,000</div>
             <p className="text-emerald-200/80 text-sm md:text-base">
               The bounty placed on the head of each problem. Solve one, and you earn a place in history—and a fortune.
             </p>
          </div>
        </section>

        {/* The Solved One: Poincaré */}
        <section className="space-y-6">
           <div className="flex items-center gap-3 mb-4">
              <div className="h-px flex-1 bg-slate-800"></div>
              <span className="text-xs font-mono uppercase tracking-widest text-slate-500">Status: 1 Solved, 6 Remain</span>
              <div className="h-px flex-1 bg-slate-800"></div>
           </div>
           
           <div className="relative group overflow-hidden rounded-3xl bg-slate-900 border border-slate-800 p-8 hover:border-emerald-500/30 transition-all duration-500">
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                 <Trophy size={120} />
              </div>
              <h3 className="text-2xl font-bold text-white mb-2">The Poincaré Conjecture</h3>
              <div className="inline-block px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 text-xs font-bold uppercase tracking-wider mb-4 border border-emerald-500/20">
                SOLVED (2003)
              </div>
              <p className="mb-4">
                Grigori Perelman, a reclusive Russian mathematician, posted a proof in 2002-2003. He famously declined the $1 million prize and the Fields Medal, stating that the knowledge itself was the reward.
              </p>
              <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 font-mono text-sm text-slate-400">
                "Every simply connected, closed 3-manifold is homeomorphic to the 3-sphere."
              </div>
           </div>
        </section>

        {/* Problem 1: P vs NP */}
        <section className="space-y-6">
           <div className="flex items-center gap-4">
              <div className="p-3 bg-indigo-500/10 text-indigo-400 rounded-xl">
                 <BinaryIcon size={24} />
              </div>
              <h3 className="text-3xl font-bold text-white">1. P vs NP</h3>
           </div>
           <div className="pl-4 border-l-2 border-indigo-500/30 space-y-4">
              <p className="text-lg text-slate-200">
                 The holy grail of computer science.
              </p>
              <p>
                 If the solution to a problem is easy to <em>check</em> for correctness, is the problem also easy to <em>solve</em>?
              </p>
              <ul className="space-y-3 mt-4">
                 <li className="flex items-start gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0"></span>
                    <span><strong>P (Polynomial Time):</strong> Problems that can be solved reasonably fast by a computer (e.g., multiplication, sorting list).</span>
                 </li>
                 <li className="flex items-start gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-purple-500 flex-shrink-0"></span>
                    <span><strong>NP (Nondeterministic Polynomial Time):</strong> Problems where a solution can be verified fast, but finding it might take billions of years (e.g., Sudoku, Protein Folding, Encryption cracking).</span>
                 </li>
              </ul>
              <div className="mt-6 p-6 rounded-2xl bg-indigo-900/10 border border-indigo-500/20">
                 <p className="text-indigo-300 italic font-medium">
                    "If P = NP, then the world would be a profoundly different place... Everyone who could appreciate a symphony would be Mozart; everyone who could follow a step-by-step argument would be Gauss."
                 </p>
                 <div className="text-right text-sm text-indigo-400/60 mt-2">— Scott Aaronson</div>
              </div>
           </div>
        </section>

        {/* Problem 2: Riemann Hypothesis */}
        <section className="space-y-6">
           <div className="flex items-center gap-4">
              <div className="p-3 bg-rose-500/10 text-rose-400 rounded-xl">
                 <Sigma size={24} />
              </div>
              <h3 className="text-3xl font-bold text-white">2. The Riemann Hypothesis</h3>
           </div>
           <div className="pl-4 border-l-2 border-rose-500/30 space-y-4">
              <p>
                 Proposed by Bernhard Riemann in 1859, this is often considered the most important unsolved problem in pure mathematics. It concerns the distribution of <strong>prime numbers</strong>.
              </p>
              <div className="bg-slate-900 p-6 rounded-2xl border border-slate-800 font-mono text-center">
                 <span className="text-2xl text-rose-300">ζ(s) = 0</span>
                 <p className="text-sm text-slate-500 mt-2">
                    All non-trivial zeros of the Riemann zeta function have a real part equal to 1/2.
                 </p>
              </div>
              <p>
                 If true, it would imply that prime numbers are distributed as regularly as possible amidst the integers. If false, the prime numbers are far more chaotic than we believe, and much of modern number theory (and cryptography) rests on shaky ground.
              </p>
           </div>
        </section>

        {/* Problem 3: Navier-Stokes */}
        <section className="space-y-6">
           <div className="flex items-center gap-4">
              <div className="p-3 bg-blue-500/10 text-blue-400 rounded-xl">
                 <Waves size={24} />
              </div>
              <h3 className="text-3xl font-bold text-white">3. Navier-Stokes Existence & Smoothness</h3>
           </div>
           <div className="pl-4 border-l-2 border-blue-500/30 space-y-4">
              <p>
                 These equations describe the motion of fluid substances—from the water flowing in a pipe to the air flow around an airplane wing.
              </p>
              <p>
                 Engineers and physicists use them every day, yet we have no mathematical proof that smooth solutions always exist. It is theoretically possible that a mathematically perfect fluid could spontaneously explode or develop "singularities" (infinite velocity) in finite time. The prize is for proving that these breakdowns either do or do not happen.
              </p>
           </div>
        </section>

        {/* The Remaining Grid */}
        <section>
           <h3 className="text-xl font-bold text-white mb-6">The Remaining Mysteries</h3>
           <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-5 rounded-2xl bg-slate-900/40 border border-slate-800 hover:bg-slate-900 hover:border-slate-700 transition-colors">
                 <h4 className="font-bold text-indigo-300 mb-2">Yang-Mills and Mass Gap</h4>
                 <p className="text-sm text-slate-400">Quantum physics. Why do subatomic particles have mass?</p>
              </div>
              <div className="p-5 rounded-2xl bg-slate-900/40 border border-slate-800 hover:bg-slate-900 hover:border-slate-700 transition-colors">
                 <h4 className="font-bold text-indigo-300 mb-2">Birch and Swinnerton-Dyer</h4>
                 <p className="text-sm text-slate-400">Algebraic geometry. Defining the number of rational points on elliptic curves.</p>
              </div>
              <div className="p-5 rounded-2xl bg-slate-900/40 border border-slate-800 hover:bg-slate-900 hover:border-slate-700 transition-colors">
                 <h4 className="font-bold text-indigo-300 mb-2">Hodge Conjecture</h4>
                 <p className="text-sm text-slate-400">Investigating the shapes of complex algebraic varieties.</p>
              </div>
           </div>
        </section>
      </div>
    )
  },
  {
    id: "incompleteness",
    title: "Gödel's Incompleteness Theorems",
    excerpt: "Why some truths in mathematics can never be proven, challenging the very foundations of logic.",
    icon: <Zap className="w-8 h-8" />,
    color: "from-rose-600 to-orange-600",
    readTime: "15 min",
    date: "Jan 12, 2024",
    tags: ["Logic", "Philosophy", "Proof"],
    content: (
      <div className="space-y-12 text-slate-300 font-light">
        {/* Intro */}
        <section className="space-y-6">
          <div className="p-6 rounded-2xl bg-amber-500/10 border border-amber-500/20 mb-8">
             <p className="font-serif italic text-xl text-amber-200 text-center">
                 "Wir müssen wissen. Wir werden wissen." <br/>
                 <span className="text-sm not-italic opacity-70">(We must know. We will know.)</span>
             </p>
             <div className="text-center text-xs font-mono uppercase tracking-widest text-amber-500/60 mt-4">— David Hilbert, 1930</div>
          </div>
          <p className="text-xl md:text-2xl leading-relaxed text-slate-200 font-normal">
             For centuries, mathematicians believed that with enough time and cleverness, every mathematical truth could be proven. They envisioned mathematics as a perfect, unshakeable tower of logic.
          </p>
          <p>
             In 1931, a 25-year-old Austrian logician named <strong>Kurt Gödel</strong> didn't just find a crack in that tower. He showed that the crack was part of the foundation itself.
          </p>
        </section>
    
        {/* The Core Mechanism: Gödel Numbering */}
        <section className="space-y-6">
           <div className="flex items-center gap-4">
              <div className="p-3 bg-indigo-500/10 text-indigo-400 rounded-xl">
                 <Hash size={24} />
              </div>
              <h3 className="text-3xl font-bold text-white">1. Turning Math into Code</h3>
           </div>
           
           <p>
              Gödel's genius wasn't just in logic, but in encoding. He realized that mathematical statements are just sequences of symbols. If we assign a unique number to every symbol, we can translate entire equations into single, giant integers.
           </p>
    
           {/* Visualization of Gödel Numbering */}
           <div className="relative my-10 p-8 rounded-3xl bg-slate-900 border border-slate-800 overflow-hidden">
               {/* Background Grid */}
               <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808008_1px,transparent_1px),linear-gradient(to_bottom,#80808008_1px,transparent_1px)] bg-[size:24px_24px]"></div>
               
               <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-8">
                   {/* Step 1: Logic */}
                   <div className="flex-1 flex flex-col items-center gap-4">
                       <div className="w-16 h-16 rounded-2xl bg-indigo-500/20 border border-indigo-500/40 flex items-center justify-center text-indigo-400">
                           <Variable size={32} />
                       </div>
                       <div className="text-center">
                           <div className="text-white font-bold">Logic</div>
                           <div className="text-xs text-slate-500 font-mono">"x + y = z"</div>
                       </div>
                   </div>
    
                   {/* Arrow */}
                   <div className="flex flex-col items-center gap-2 text-slate-600">
                       <div className="text-[10px] font-mono uppercase tracking-widest">Map</div>
                       <ArrowRight size={24} />
                   </div>
    
                   {/* Step 2: Number */}
                   <div className="flex-1 flex flex-col items-center gap-4">
                       <div className="w-16 h-16 rounded-2xl bg-rose-500/20 border border-rose-500/40 flex items-center justify-center text-rose-400">
                           <Hash size={32} />
                       </div>
                       <div className="text-center">
                           <div className="text-white font-bold">Number</div>
                           <div className="text-xs text-slate-500 font-mono">2^x * 3^y ...</div>
                       </div>
                   </div>
                   
                   {/* Arrow */}
                   <div className="flex flex-col items-center gap-2 text-slate-600">
                       <div className="text-[10px] font-mono uppercase tracking-widest">Prove</div>
                       <ArrowRight size={24} />
                   </div>
    
                   {/* Step 3: Meta-Logic */}
                   <div className="flex-1 flex flex-col items-center gap-4">
                       <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
                           <Brain size={32} />
                       </div>
                       <div className="text-center">
                           <div className="text-white font-bold">Meta-Truth</div>
                           <div className="text-xs text-slate-500 font-mono">Unprovable Truths</div>
                       </div>
                   </div>
               </div>
           </div>
           
           <p className="text-sm text-slate-400 border-l-2 border-slate-700 pl-4">
              This allowed math to talk about itself. Just as a computer program can process its own source code as text, arithmetic can calculate properties about arithmetic proofs.
           </p>
        </section>
    
        {/* The Liar's Loop */}
        <section className="space-y-8">
            <h3 className="text-3xl font-bold text-white">2. The Self-Destructing Sentence</h3>
            <p>
               Gödel constructed a specific mathematical statement, let's call it <strong>G</strong>. 
               Through complex numbering, <strong>G</strong> essentially translates to:
            </p>
            
            <div className="relative group cursor-pointer">
                <div className="absolute -inset-1 bg-gradient-to-r from-rose-500 to-orange-500 rounded-2xl blur opacity-20 group-hover:opacity-40 transition duration-500"></div>
                <div className="relative p-8 rounded-2xl bg-slate-900 border border-slate-800 text-center space-y-4">
                    <div className="text-4xl md:text-5xl font-bold text-white">
                        "This statement cannot be proven."
                    </div>
                </div>
            </div>
    
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="p-6 rounded-2xl bg-slate-900/50 border border-rose-500/20 hover:bg-slate-900 transition-colors">
                     <h4 className="text-rose-400 font-bold mb-2 flex items-center gap-2">
                        <ShieldAlert size={18} /> Scenario A: G is False
                     </h4>
                     <p className="text-sm text-slate-400">
                        If G is false, then "This statement cannot be proven" is false. 
                        This means G <strong>can</strong> be proven. 
                        <br/><br/>
                        But if G can be proven, it must be true (assuming math doesn't lie). 
                        <br/>
                        <span className="text-white font-bold">Contradiction!</span>
                     </p>
                </div>
                <div className="p-6 rounded-2xl bg-slate-900/50 border border-emerald-500/20 hover:bg-slate-900 transition-colors">
                     <h4 className="text-emerald-400 font-bold mb-2 flex items-center gap-2">
                        <CheckCircle2 size={18} /> Scenario B: G is True
                     </h4>
                     <p className="text-sm text-slate-400">
                        If G is true, then "This statement cannot be proven" is true.
                        <br/><br/>
                        This means G is a <strong>true statement</strong> that mathematics <strong>cannot prove</strong>.
                        <br/>
                        <span className="text-white font-bold">Incompleteness!</span>
                     </p>
                </div>
            </div>
        </section>
    
        {/* The Fallout */}
        <section className="space-y-6">
            <h3 className="text-2xl font-bold text-white">The Legacy</h3>
            <p>
                This destroyed Hilbert's dream. We now know that in any logical system complex enough to do basic math:
            </p>
            <ul className="space-y-4">
                <li className="flex gap-4">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center font-bold text-slate-200">1</div>
                    <div>
                        <strong className="text-white block">Incompleteness</strong>
                        There will always be true statements that cannot be proven within the system.
                    </div>
                </li>
                <li className="flex gap-4">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-800 flex items-center justify-center font-bold text-slate-200">2</div>
                    <div>
                        <strong className="text-white block">No Consistency Proof</strong>
                        The system cannot prove its own consistency. If a system can prove it creates no contradictions, it is lying.
                    </div>
                </li>
            </ul>
            <p className="text-slate-400 italic mt-8">
                Far from breaking mathematics, this limit gave birth to computer science. Alan Turing took Gödel's concept of numbering and logic loops to define the "Halting Problem," creating the theoretical model for the computer you're using right now.
            </p>
        </section>
      </div>
    )
  },
  {
    id: "graph-theory",
    title: "Social Networks & Graph Theory",
    excerpt: "Analyzing the six degrees of separation through the lens of nodes, edges, and small-world networks.",
    icon: <Network className="w-8 h-8" />,
    color: "from-blue-600 to-cyan-500",
    readTime: "18 min",
    date: "Dec 05, 2023",
    tags: ["Networks", "Algorithms", "Topology"],
    content: (
      <div className="space-y-8 text-slate-300">
         <p>Everything is connected. Graph theory provides the mathematical structure to model pairwise relations between objects.</p>
         <div className="p-6 bg-slate-900 border border-slate-800 rounded-2xl">
            From the routing algorithms that power the internet to the friend suggestions on your social feed, graphs are the invisible skeleton of the digital age.
         </div>
      </div>
    )
  },
  {
    id: "quantum-basics",
    title: "Quantum Superposition for Devs",
    excerpt: "Understanding Qubits without the dense physics. How quantum logic differs from classical binary.",
    icon: <Atom className="w-8 h-8" />,
    color: "from-violet-600 to-fuchsia-600",
    readTime: "22 min",
    date: "Nov 20, 2023",
    tags: ["Quantum Computing", "Qubits", "Physics"],
    content: (
      <div className="space-y-8 text-slate-300">
         <p>Classical computers think in 0s and 1s. Quantum computers think in probabilities.</p>
         <p>This shift from deterministic bits to probabilistic qubits allows for parallel computation on a scale that defies classical logic.</p>
      </div>
    )
  },
  {
    id: "cryptography",
    title: "The Math Behind Encryption",
    excerpt: "How prime numbers keep your credit card safe. A look at RSA and Elliptic Curve Cryptography.",
    icon: <Lock className="w-8 h-8" />,
    color: "from-amber-500 to-orange-500",
    readTime: "14 min",
    date: "Oct 11, 2023",
    tags: ["Security", "Primes", "RSA"],
    content: (
      <div className="space-y-8 text-slate-300">
         <p>Modern security relies on the fact that multiplying two large prime numbers is easy, but factoring the result back into those primes is incredibly hard.</p>
      </div>
    )
  }
];

const BlogSection: React.FC<{ onOpenChange: (isOpen: boolean) => void }> = ({ onOpenChange }) => {
  const [activePost, setActivePost] = useState<BlogPost | null>(null);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [readingProgress, setReadingProgress] = useState(0);
  const overlayRef = useRef<HTMLDivElement>(null);

  // Dynamic SEO Injection
  useEffect(() => {
    if (!activePost) return;

    // Store previous document title
    const previousTitle = document.title;
    document.title = `${activePost.title} | Shahad Uddin`;

    // Define Meta Tags to Update
    const metaTags = [
        { name: 'description', content: activePost.excerpt },
        { property: 'og:title', content: activePost.title },
        { property: 'og:description', content: activePost.excerpt },
        { property: 'og:type', content: 'article' },
        { property: 'og:image', content: 'https://shahaduddin.github.io/profile.jpg' }, // Fallback to profile or specific image
    ];

    const originalMetaContents: { element: HTMLMetaElement, original: string | null }[] = [];

    // Update Meta Tags
    metaTags.forEach(tag => {
        const selector = tag.name ? `meta[name="${tag.name}"]` : `meta[property="${tag.property}"]`;
        let element = document.querySelector(selector) as HTMLMetaElement;
        
        if (!element) {
            element = document.createElement('meta');
            if (tag.name) element.setAttribute('name', tag.name);
            if (tag.property) element.setAttribute('property', tag.property);
            document.head.appendChild(element);
            originalMetaContents.push({ element, original: null });
        } else {
            originalMetaContents.push({ element, original: element.getAttribute('content') });
        }
        
        element.setAttribute('content', tag.content);
    });

    // Inject JSON-LD Schema
    const scriptId = 'blog-post-schema';
    let script = document.getElementById(scriptId) as HTMLScriptElement;
    if (script) script.remove();

    script = document.createElement('script');
    script.id = scriptId;
    script.type = 'application/ld+json';
    
    // Parse Date for Schema (e.g. "March 15, 2024" -> ISO)
    const dateObj = new Date(activePost.date);
    const isoDate = !isNaN(dateObj.getTime()) ? dateObj.toISOString() : new Date().toISOString();

    const schemaData = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": activePost.title,
        "description": activePost.excerpt,
        "author": {
            "@type": "Person",
            "name": "Shahad Uddin",
            "url": "https://shahaduddin.github.io"
        },
        "datePublished": isoDate,
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": window.location.href
        },
        "keywords": activePost.tags.join(", ")
    };

    script.text = JSON.stringify(schemaData);
    document.head.appendChild(script);

    // Cleanup Function
    return () => {
        document.title = previousTitle;
        
        originalMetaContents.forEach(({ element, original }) => {
            if (original === null) {
                element.remove();
            } else {
                element.setAttribute('content', original);
            }
        });

        if (script) script.remove();
    };
  }, [activePost]);

  const openPost = (post: BlogPost) => {
    setActivePost(post);
    onOpenChange(true);
    setReadingProgress(0);
    if (overlayRef.current) overlayRef.current.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const closePost = () => {
    setActivePost(null);
    onOpenChange(false);
    setReadingProgress(0);
  };

  const switchPost = (post: BlogPost) => {
    setActivePost(post);
    setIsSidebarOpen(false);
    setReadingProgress(0);
    if (overlayRef.current) overlayRef.current.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleScroll = () => {
    if (overlayRef.current) {
      const { scrollTop, scrollHeight, clientHeight } = overlayRef.current;
      const totalScrollableHeight = scrollHeight - clientHeight;
      if (totalScrollableHeight > 0) {
        setReadingProgress((scrollTop / totalScrollableHeight) * 100);
      }
    }
  };

  // Safe Index Calculation
  const currentIndex = activePost ? blogPosts.findIndex(bp => bp.id === activePost.id) : -1;
  const prevPost = currentIndex > 0 ? blogPosts[currentIndex - 1] : null;
  const nextPost = (currentIndex !== -1 && currentIndex < blogPosts.length - 1) ? blogPosts[currentIndex + 1] : null;

  return (
    <section id="blog" className="py-24 px-4 bg-slate-950 relative overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-indigo-600/5 rounded-full blur-[150px] -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>

      <div className="max-w-7xl mx-auto relative z-10">
        <div className="flex items-center gap-4 mb-16">
          <span className="h-px flex-1 bg-slate-800"></span>
          <h2 className="text-slate-500 font-mono uppercase tracking-widest text-sm">Mathematical Journal</h2>
          <span className="h-px flex-1 bg-slate-800"></span>
        </div>

        <div className="mb-16 text-center lg:text-left">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4 tracking-tight">Deep Dives & Discussions</h2>
          <p className="text-slate-400 text-lg max-w-2xl">
            Where abstract concepts meet digital reality. Explorations into the problems that keep mathematicians awake at night.
          </p>
        </div>

        {/* Masonry Layout Container */}
        <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
          {blogPosts.map((postItem) => (
            <div 
              key={postItem.id}
              onClick={() => openPost(postItem)}
              className="break-inside-avoid mb-6 glass-card rounded-3xl p-8 group cursor-pointer hover:border-indigo-500/50 transition-all duration-500 hover:-translate-y-2 flex flex-col border border-slate-800/50 relative overflow-hidden bg-slate-900/40"
            >
              {/* Card Header: Icon & Meta */}
              <div className="flex justify-between items-start mb-6">
                <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${postItem.color} flex items-center justify-center text-white group-hover:scale-110 transition-transform duration-500 shadow-lg ring-1 ring-white/10`}>
                  {React.cloneElement(postItem.icon as React.ReactElement<any>, { size: 20 })}
                </div>
                
                <div className="flex flex-col items-end text-[10px] font-mono text-slate-500 uppercase tracking-widest gap-1">
                  <span className="flex items-center gap-1.5"><Clock size={12} className="text-slate-600" /> {postItem.readTime}</span>
                  <span>{postItem.date}</span>
                </div>
              </div>

              {/* Title Area */}
              <h3 className="text-xl md:text-2xl font-bold text-white mb-4 group-hover:text-indigo-400 transition-colors leading-tight">
                {postItem.title}
              </h3>
              
              {/* Visual Separator */}
              <div className="h-px w-full bg-gradient-to-r from-slate-800 via-slate-700 to-slate-800 mb-5 group-hover:from-indigo-500/50 group-hover:via-indigo-400/50 group-hover:to-indigo-500/50 transition-all duration-500"></div>

              {/* Enhanced Excerpt */}
              <p className="text-slate-400 group-hover:text-slate-300 text-base mb-6 leading-7 font-normal transition-colors">
                {postItem.excerpt}
              </p>

              {/* Tags Row */}
              <div className="flex flex-wrap gap-2 mb-6">
                {postItem.tags.map((tag) => (
                  <span 
                    key={tag} 
                    className="px-2.5 py-1 rounded-md bg-slate-950 border border-slate-800 text-[10px] font-mono text-slate-500 group-hover:border-indigo-500/30 group-hover:text-indigo-300/80 transition-all duration-300"
                  >
                    #{tag}
                  </span>
                ))}
              </div>

              {/* Footer Action */}
              <div className="mt-auto flex items-center justify-between border-t border-slate-800/50 pt-5">
                <span className="text-xs font-bold text-indigo-400 group-hover:text-white transition-colors uppercase tracking-wider flex items-center gap-2 group-hover:gap-3">
                  Read Article <ArrowUpRight size={14} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Blog Overlay Implementation */}
      {activePost && (
        <div 
          ref={overlayRef}
          id="blog-overlay" 
          onScroll={handleScroll}
          className="fixed inset-0 z-[100] bg-slate-950 overflow-y-auto animate-in fade-in duration-500 flex flex-col"
        >
          {/* Main Top Header */}
          <nav className="sticky top-0 w-full z-[110] bg-slate-950/80 backdrop-blur-xl border-b border-slate-800">
            <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <button 
                  onClick={closePost}
                  className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors group"
                >
                  <div className="p-2 rounded-lg bg-slate-900 border border-slate-800 group-hover:border-indigo-500 group-hover:text-indigo-400 transition-all">
                    <ArrowLeft size={20} />
                  </div>
                  <span className="font-medium hidden sm:block">Exit Reader</span>
                </button>
                <div className="h-8 w-px bg-slate-800 hidden md:block"></div>
                <button 
                  onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                  className="lg:hidden flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 hover:text-white transition-all"
                >
                  <List size={18} />
                  <span className="text-xs font-mono">Posts</span>
                </button>
              </div>
              
              <div className="flex items-center gap-4">
                <button className="p-2 text-slate-400 hover:text-indigo-400 transition-colors">
                  <Share2 size={20} />
                </button>
                <div className="h-10 w-px bg-slate-800 hidden sm:block"></div>
                <div className="text-indigo-500 font-mono text-xs hidden md:block uppercase tracking-widest">{activePost.id}</div>
              </div>
            </div>
          </nav>

          <div className="flex flex-1 relative max-w-7xl mx-auto w-full">
            {/* Navigation Sidebar */}
            <aside className={`
              lg:block lg:sticky lg:top-20 lg:h-[calc(100vh-5rem)] 
              ${isSidebarOpen ? 'fixed inset-0 z-[120] bg-slate-950 p-6' : 'hidden lg:p-10 lg:w-80'}
            `}>
              <div className="flex flex-col h-full">
                {isSidebarOpen && (
                  <div className="flex justify-between items-center mb-10">
                    <h3 className="text-xl font-bold text-white">Journal Entries</h3>
                    <button onClick={() => setIsSidebarOpen(false)} className="p-2 text-slate-400"><ArrowLeft size={24} /></button>
                  </div>
                )}
                
                <h4 className="text-slate-500 font-mono uppercase tracking-widest text-[10px] mb-6 px-4">Catalog</h4>
                
                <div className="space-y-2">
                  {blogPosts.map((sidebarItem) => (
                    <button
                      key={sidebarItem.id}
                      onClick={() => switchPost(sidebarItem)}
                      className={`w-full text-left p-4 rounded-2xl transition-all duration-300 flex items-center gap-4 group ${
                        activePost.id === sidebarItem.id 
                          ? 'bg-indigo-600/10 border border-indigo-500/20 text-indigo-300' 
                          : 'hover:bg-slate-900 border border-transparent text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      <div className={`p-2 rounded-lg ${activePost.id === sidebarItem.id ? 'bg-indigo-500/20 text-indigo-400' : 'bg-slate-800 text-slate-500 group-hover:text-slate-300 group-hover:bg-slate-700'} transition-all`}>
                        {React.cloneElement(sidebarItem.icon as React.ReactElement<any>, { size: 18 })}
                      </div>
                      <span className="text-sm font-semibold leading-tight line-clamp-1">{sidebarItem.title}</span>
                    </button>
                  ))}
                </div>
              </div>
            </aside>

            {/* Reading Content Area */}
            <main className="flex-1 px-6 lg:px-12 py-12 lg:py-20 border-l border-slate-900 min-h-screen">
              <article className="max-w-3xl mx-auto">
                {/* Meta Header */}
                <header className="mb-16 space-y-8">
                  <div className="inline-flex items-center gap-3 px-4 py-2 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-sm font-mono">
                     <Sigma size={16} />
                     <span>Journal Entry #{activePost.id}</span>
                  </div>
                  
                  <h1 className="text-5xl md:text-7xl font-extrabold text-white tracking-tight leading-[1.1]">
                    {activePost.title}
                  </h1>

                  <div className="flex flex-wrap items-center gap-6 text-slate-500 font-medium">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-full bg-indigo-600/20 flex items-center justify-center text-indigo-400 font-bold">
                        S
                      </div>
                      <span className="text-sm">Shahad Uddin</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                       <Clock size={16} />
                       <span>{activePost.readTime} read</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                       <span>{activePost.date}</span>
                    </div>
                  </div>
                </header>

                {/* Content Body */}
                <div className="prose prose-invert prose-lg max-w-none text-slate-400">
                  {activePost.content}
                </div>

                {/* Post Navigation */}
                <nav className="mt-20 grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {prevPost ? (
                    <button 
                      onClick={() => switchPost(prevPost)}
                      className="group flex flex-col items-start p-6 rounded-2xl bg-slate-900/50 border border-slate-800 hover:border-indigo-500/50 transition-all text-left"
                    >
                      <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-3">Previous Entry</span>
                      <span className="text-white font-bold text-lg leading-tight group-hover:text-indigo-300 transition-colors">
                        {prevPost.title}
                      </span>
                    </button>
                  ) : <div />}

                  {nextPost ? (
                    <button 
                      onClick={() => switchPost(nextPost)}
                      className="group flex flex-col items-end p-6 rounded-2xl bg-slate-900/50 border border-slate-800 hover:border-indigo-500/50 transition-all text-right"
                    >
                      <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-3">Next Entry</span>
                      <span className="text-white font-bold text-lg leading-tight group-hover:text-indigo-300 transition-colors">
                        {nextPost.title}
                      </span>
                    </button>
                  ) : <div />}
                </nav>
              </article>
            </main>
          </div>

          {/* Reading Progress Bar */}
          <div className="fixed top-0 left-0 w-full h-1 z-[120] pointer-events-none">
             <div 
              className="h-full bg-gradient-to-r from-indigo-500 to-cyan-400 transition-all duration-150 ease-out shadow-[0_0_10px_rgba(99,102,241,0.5)]"
              style={{ width: `${readingProgress}%` }}
             ></div>
          </div>
        </div>
      )}
    </section>
  );
};

export default BlogSection;
