
import React, { useState, useEffect, useRef } from 'react';
import { 
  BookOpen, Sparkles, Sigma, Zap, ArrowLeft, Clock, Share2, Maximize2, 
  Infinity, RefreshCw, Compass, Trophy, Brain, Layers, Waves, Target, 
  Binary as BinaryIcon, ShieldAlert, Puzzle, Scale, History, ShieldCheck, 
  Search, Database, List, Microscope, TrendingUp, Wind, Droplets, 
  ChevronLeft, ChevronRight, Atom, Shield, Variable, FunctionSquare,
  Grid3X3, Shapes, GitMerge, Calculator, Network, Box, Lock, ArrowUpRight
} from 'lucide-react';

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: React.ReactNode;
  icon: React.ReactNode;
  color: string;
  readTime: string;
  date: string;
  tags: string[];
}

const blogPosts: BlogPost[] = [
  {
    id: "fractals",
    title: "Fractals: The Hidden Geometry of Nature",
    excerpt: "Exploring the Mandelbrot set and how infinite complexity arises from simple recursive equations.",
    icon: <Sparkles className="w-8 h-8" />,
    color: "from-purple-600 to-indigo-600",
    readTime: "12 min",
    date: "March 15, 2024",
    tags: ["Geometry", "Recursion", "Chaos Theory"],
    content: (
      <div className="space-y-10 text-slate-300">
        <section className="space-y-4">
          <p className="text-xl leading-relaxed text-slate-200">
            For centuries, Euclidean geometry—with its clean lines, perfect circles, and smooth planes—was the only language we had to describe the physical world. But nature is rarely smooth. Clouds are not spheres; mountains are not cones.
          </p>
          <p>
            In 1975, Benoît Mandelbrot coined the term <strong>"Fractal"</strong> (from the Latin <em>fractus</em>, meaning broken or fractured) to describe a new kind of geometry that accounts for the jagged, irregular, and infinitely complex patterns found everywhere in the universe.
          </p>
        </section>

        <section className="p-8 rounded-3xl bg-slate-900/50 border border-slate-800 space-y-6">
          <div className="flex items-center gap-3 text-indigo-400 mb-2">
            <Infinity size={24} />
            <h3 className="text-2xl font-bold text-white">The Core Principle: Self-Similarity</h3>
          </div>
          <p>
            The defining characteristic of a fractal is <strong>self-similarity</strong>. If you zoom into a fractal, you find smaller versions of the whole. This pattern repeats forever. Whether you are looking at the entire set or a microscopic detail, the structural complexity remains constant.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-center">
              <div className="text-indigo-500 font-bold mb-1">Macro</div>
              <p className="text-xs text-slate-500">The entire galaxy cluster</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-center">
              <div className="text-purple-500 font-bold mb-1">Meso</div>
              <p className="text-xs text-slate-500">A single lightning bolt</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-center">
              <div className="text-pink-500 font-bold mb-1">Micro</div>
              <p className="text-xs text-slate-500">The branching of a lung</p>
            </div>
          </div>
        </section>

        <section className="space-y-6">
          <div className="flex items-center gap-3 text-emerald-400 mb-2">
            <RefreshCw size={24} />
            <h3 className="text-2xl font-bold text-white">The Mandelbrot Set: Elegant Simplicity</h3>
          </div>
          <p>
            The most famous fractal is the Mandelbrot Set. It is generated by a deceptively simple iterative process in the complex plane:
          </p>
          <div className="relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-2xl blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
            <div className="relative bg-slate-950 p-8 rounded-2xl border border-slate-800 font-mono text-center overflow-hidden">
               <span className="text-3xl md:text-4xl text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">
                {"z_{n+1} = z_n^2 + c"}
               </span>
               <div className="mt-4 text-sm text-slate-500 italic">where z and c are complex numbers</div>
            </div>
          </div>
          <p>
            We start with <code className="text-indigo-400">z = 0</code>. For every point <code className="text-indigo-400">c</code> in the complex plane, we repeat this calculation. If the value of <code className="text-indigo-400">z</code> stays bounded (doesn't fly off to infinity), that point <code className="text-indigo-400">c</code> is part of the Mandelbrot Set.
          </p>
        </section>
      </div>
    )
  },
  {
    id: "millennium",
    title: "The 7 Millennium Prize Problems",
    excerpt: "A deep dive into the unsolved mysteries that define modern mathematics and carry a $1,000,000 reward.",
    icon: <Sigma className="w-8 h-8" />,
    color: "from-emerald-600 to-teal-600",
    readTime: "35 min",
    date: "Feb 28, 2024",
    tags: ["Millennium Prize", "Complexity", "Physics"],
    content: (
      <div className="space-y-12 text-slate-300">
        <section className="space-y-4">
          <p className="text-xl leading-relaxed text-slate-200">
            On May 24, 2000, the Clay Mathematics Institute established a list of seven problems to celebrate mathematics in the new millennium. These aren't just difficult puzzles; they are the fundamental missing links in our understanding of physics, logic, and computation.
          </p>
        </section>

        {/* Problem #1: P vs NP */}
        <section className="space-y-8">
          <div className="flex items-center gap-4 border-l-4 border-indigo-500 pl-6">
            <div className="p-3 bg-indigo-500/10 text-indigo-400 rounded-xl">
              <BinaryIcon size={32} />
            </div>
            <div>
              <h3 className="text-3xl font-bold text-white">Problem #1: P vs NP</h3>
              <p className="text-indigo-400 font-mono text-sm tracking-widest">Complexity Theory</p>
            </div>
          </div>
          <div className="bg-slate-900/80 p-8 rounded-3xl border border-slate-800 space-y-6">
            <p>Informally: <strong>Can every problem whose solution can be quickly verified also be quickly solved?</strong></p>
          </div>
        </section>
      </div>
    )
  },
  {
    id: "incompleteness",
    title: "Gödel's Incompleteness Theorems",
    excerpt: "Why some truths in mathematics can never be proven, challenging the very foundations of logic.",
    icon: <Zap className="w-8 h-8" />,
    color: "from-rose-600 to-orange-600",
    readTime: "15 min",
    date: "Jan 12, 2024",
    tags: ["Logic", "Philosophy", "Proof"],
    content: (
      <div className="space-y-10 text-slate-300">
        <p className="text-xl leading-relaxed text-slate-200">
            In the early 20th century, the mathematical world was gripped by a quest for absolute certainty. David Hilbert proposed a grand challenge: to find a complete and consistent set of axioms for all of mathematics.
        </p>
        <p>
            But in 1931, a 25-year-old logician named <strong>Kurt Gödel</strong> published a paper that destroyed this dream forever.
        </p>
      </div>
    )
  },
  {
    id: "graph-theory",
    title: "Social Networks & Graph Theory",
    excerpt: "Analyzing the six degrees of separation through the lens of nodes, edges, and small-world networks.",
    icon: <Network className="w-8 h-8" />,
    color: "from-blue-600 to-cyan-500",
    readTime: "18 min",
    date: "Dec 05, 2023",
    tags: ["Networks", "Algorithms", "Topology"],
    content: (
      <div className="space-y-8 text-slate-300">
         <p>Everything is connected. Graph theory provides the mathematical structure to model pairwise relations between objects.</p>
         <div className="p-6 bg-slate-900 border border-slate-800 rounded-2xl">
            From the routing algorithms that power the internet to the friend suggestions on your social feed, graphs are the invisible skeleton of the digital age.
         </div>
      </div>
    )
  },
  {
    id: "quantum-basics",
    title: "Quantum Superposition for Devs",
    excerpt: "Understanding Qubits without the dense physics. How quantum logic differs from classical binary.",
    icon: <Atom className="w-8 h-8" />,
    color: "from-violet-600 to-fuchsia-600",
    readTime: "22 min",
    date: "Nov 20, 2023",
    tags: ["Quantum Computing", "Qubits", "Physics"],
    content: (
      <div className="space-y-8 text-slate-300">
         <p>Classical computers think in 0s and 1s. Quantum computers think in probabilities.</p>
         <p>This shift from deterministic bits to probabilistic qubits allows for parallel computation on a scale that defies classical logic.</p>
      </div>
    )
  },
  {
    id: "cryptography",
    title: "The Math Behind Encryption",
    excerpt: "How prime numbers keep your credit card safe. A look at RSA and Elliptic Curve Cryptography.",
    icon: <Lock className="w-8 h-8" />,
    color: "from-amber-500 to-orange-500",
    readTime: "14 min",
    date: "Oct 11, 2023",
    tags: ["Security", "Primes", "RSA"],
    content: (
      <div className="space-y-8 text-slate-300">
         <p>Modern security relies on the fact that multiplying two large prime numbers is easy, but factoring the result back into those primes is incredibly hard.</p>
      </div>
    )
  }
];

const BlogSection: React.FC<{ onOpenChange: (isOpen: boolean) => void }> = ({ onOpenChange }) => {
  const [activePost, setActivePost] = useState<BlogPost | null>(null);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [readingProgress, setReadingProgress] = useState(0);
  const overlayRef = useRef<HTMLDivElement>(null);

  const openPost = (post: BlogPost) => {
    setActivePost(post);
    onOpenChange(true);
    setReadingProgress(0);
    if (overlayRef.current) overlayRef.current.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const closePost = () => {
    setActivePost(null);
    onOpenChange(false);
    setReadingProgress(0);
  };

  const switchPost = (post: BlogPost) => {
    setActivePost(post);
    setIsSidebarOpen(false);
    setReadingProgress(0);
    if (overlayRef.current) overlayRef.current.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleScroll = () => {
    if (overlayRef.current) {
      const { scrollTop, scrollHeight, clientHeight } = overlayRef.current;
      const totalScrollableHeight = scrollHeight - clientHeight;
      if (totalScrollableHeight > 0) {
        setReadingProgress((scrollTop / totalScrollableHeight) * 100);
      }
    }
  };

  // Safe Index Calculation
  const currentIndex = activePost ? blogPosts.findIndex(bp => bp.id === activePost.id) : -1;
  const prevPost = currentIndex > 0 ? blogPosts[currentIndex - 1] : null;
  const nextPost = (currentIndex !== -1 && currentIndex < blogPosts.length - 1) ? blogPosts[currentIndex + 1] : null;

  return (
    <section id="blog" className="py-24 px-4 bg-slate-950 relative overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-indigo-600/5 rounded-full blur-[150px] -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>

      <div className="max-w-7xl mx-auto relative z-10">
        <div className="flex items-center gap-4 mb-16">
          <span className="h-px flex-1 bg-slate-800"></span>
          <h2 className="text-slate-500 font-mono uppercase tracking-widest text-sm">Mathematical Journal</h2>
          <span className="h-px flex-1 bg-slate-800"></span>
        </div>

        <div className="mb-16 text-center lg:text-left">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4 tracking-tight">Deep Dives & Discussions</h2>
          <p className="text-slate-400 text-lg max-w-2xl">
            Where abstract concepts meet digital reality. Explorations into the problems that keep mathematicians awake at night.
          </p>
        </div>

        {/* Masonry Layout Container */}
        <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
          {blogPosts.map((postItem) => (
            <div 
              key={postItem.id}
              onClick={() => openPost(postItem)}
              className="break-inside-avoid mb-6 glass-card rounded-3xl p-8 group cursor-pointer hover:border-indigo-500/50 transition-all duration-500 hover:-translate-y-2 flex flex-col border border-slate-800/50 relative overflow-hidden bg-slate-900/40"
            >
              {/* Card Header: Icon & Meta */}
              <div className="flex justify-between items-start mb-6">
                <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${postItem.color} flex items-center justify-center text-white group-hover:scale-110 transition-transform duration-500 shadow-lg ring-1 ring-white/10`}>
                  {React.cloneElement(postItem.icon as React.ReactElement<any>, { size: 20 })}
                </div>
                
                <div className="flex flex-col items-end text-[10px] font-mono text-slate-500 uppercase tracking-widest gap-1">
                  <span className="flex items-center gap-1.5"><Clock size={12} className="text-slate-600" /> {postItem.readTime}</span>
                  <span>{postItem.date}</span>
                </div>
              </div>

              {/* Title Area */}
              <h3 className="text-xl md:text-2xl font-bold text-white mb-4 group-hover:text-indigo-400 transition-colors leading-tight">
                {postItem.title}
              </h3>
              
              {/* Visual Separator */}
              <div className="h-px w-full bg-gradient-to-r from-slate-800 via-slate-700 to-slate-800 mb-5 group-hover:from-indigo-500/50 group-hover:via-indigo-400/50 group-hover:to-indigo-500/50 transition-all duration-500"></div>

              {/* Enhanced Excerpt */}
              <p className="text-slate-400 group-hover:text-slate-300 text-base mb-6 leading-7 font-normal transition-colors">
                {postItem.excerpt}
              </p>

              {/* Tags Row */}
              <div className="flex flex-wrap gap-2 mb-6">
                {postItem.tags.map((tag) => (
                  <span 
                    key={tag} 
                    className="px-2.5 py-1 rounded-md bg-slate-950 border border-slate-800 text-[10px] font-mono text-slate-500 group-hover:border-indigo-500/30 group-hover:text-indigo-300/80 transition-all duration-300"
                  >
                    #{tag}
                  </span>
                ))}
              </div>

              {/* Footer Action */}
              <div className="mt-auto flex items-center justify-between border-t border-slate-800/50 pt-5">
                <span className="text-xs font-bold text-indigo-400 group-hover:text-white transition-colors uppercase tracking-wider flex items-center gap-2 group-hover:gap-3">
                  Read Article <ArrowUpRight size={14} className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Blog Overlay Implementation */}
      {activePost && (
        <div 
          ref={overlayRef}
          id="blog-overlay" 
          onScroll={handleScroll}
          className="fixed inset-0 z-[100] bg-slate-950 overflow-y-auto animate-in fade-in duration-500 flex flex-col"
        >
          {/* Main Top Header */}
          <nav className="sticky top-0 w-full z-[110] bg-slate-950/80 backdrop-blur-xl border-b border-slate-800">
            <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <button 
                  onClick={closePost}
                  className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors group"
                >
                  <div className="p-2 rounded-lg bg-slate-900 border border-slate-800 group-hover:border-indigo-500 group-hover:text-indigo-400 transition-all">
                    <ArrowLeft size={20} />
                  </div>
                  <span className="font-medium hidden sm:block">Exit Reader</span>
                </button>
                <div className="h-8 w-px bg-slate-800 hidden md:block"></div>
                <button 
                  onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                  className="lg:hidden flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 hover:text-white transition-all"
                >
                  <List size={18} />
                  <span className="text-xs font-mono">Posts</span>
                </button>
              </div>
              
              <div className="flex items-center gap-4">
                <button className="p-2 text-slate-400 hover:text-indigo-400 transition-colors">
                  <Share2 size={20} />
                </button>
                <div className="h-10 w-px bg-slate-800 hidden sm:block"></div>
                <div className="text-indigo-500 font-mono text-xs hidden md:block uppercase tracking-widest">{activePost.id}</div>
              </div>
            </div>
          </nav>

          <div className="flex flex-1 relative max-w-7xl mx-auto w-full">
            {/* Navigation Sidebar */}
            <aside className={`
              lg:block lg:sticky lg:top-20 lg:h-[calc(100vh-5rem)] 
              ${isSidebarOpen ? 'fixed inset-0 z-[120] bg-slate-950 p-6' : 'hidden lg:p-10 lg:w-80'}
            `}>
              <div className="flex flex-col h-full">
                {isSidebarOpen && (
                  <div className="flex justify-between items-center mb-10">
                    <h3 className="text-xl font-bold text-white">Journal Entries</h3>
                    <button onClick={() => setIsSidebarOpen(false)} className="p-2 text-slate-400"><ArrowLeft size={24} /></button>
                  </div>
                )}
                
                <h4 className="text-slate-500 font-mono uppercase tracking-widest text-[10px] mb-6 px-4">Catalog</h4>
                
                <div className="space-y-2">
                  {blogPosts.map((sidebarItem) => (
                    <button
                      key={sidebarItem.id}
                      onClick={() => switchPost(sidebarItem)}
                      className={`w-full text-left p-4 rounded-2xl transition-all duration-300 flex items-center gap-4 group ${
                        activePost.id === sidebarItem.id 
                          ? 'bg-indigo-600/10 border border-indigo-500/20 text-indigo-300' 
                          : 'hover:bg-slate-900 border border-transparent text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      <div className={`p-2 rounded-lg ${activePost.id === sidebarItem.id ? 'bg-indigo-500/20 text-indigo-400' : 'bg-slate-800 text-slate-500 group-hover:text-slate-300 group-hover:bg-slate-700'} transition-all`}>
                        {React.cloneElement(sidebarItem.icon as React.ReactElement<any>, { size: 18 })}
                      </div>
                      <span className="text-sm font-semibold leading-tight line-clamp-1">{sidebarItem.title}</span>
                    </button>
                  ))}
                </div>
              </div>
            </aside>

            {/* Reading Content Area */}
            <main className="flex-1 px-6 lg:px-12 py-12 lg:py-20 border-l border-slate-900 min-h-screen">
              <article className="max-w-3xl mx-auto">
                {/* Meta Header */}
                <header className="mb-16 space-y-8">
                  <div className="inline-flex items-center gap-3 px-4 py-2 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-sm font-mono">
                     <Sigma size={16} />
                     <span>Journal Entry #{activePost.id}</span>
                  </div>
                  
                  <h1 className="text-5xl md:text-7xl font-extrabold text-white tracking-tight leading-[1.1]">
                    {activePost.title}
                  </h1>

                  <div className="flex flex-wrap items-center gap-6 text-slate-500 font-medium">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-full bg-indigo-600/20 flex items-center justify-center text-indigo-400 font-bold">
                        S
                      </div>
                      <span className="text-sm">Shahad Uddin</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                       <Clock size={16} />
                       <span>{activePost.readTime} read</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                       <span>{activePost.date}</span>
                    </div>
                  </div>
                </header>

                {/* Content Body */}
                <div className="prose prose-invert prose-lg max-w-none text-slate-400">
                  {activePost.content}
                </div>

                {/* Post Navigation */}
                <nav className="mt-20 grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {prevPost ? (
                    <button 
                      onClick={() => switchPost(prevPost)}
                      className="group flex flex-col items-start p-6 rounded-2xl bg-slate-900/50 border border-slate-800 hover:border-indigo-500/50 transition-all text-left"
                    >
                      <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-3">Previous Entry</span>
                      <span className="text-white font-bold text-lg leading-tight group-hover:text-indigo-300 transition-colors">
                        {prevPost.title}
                      </span>
                    </button>
                  ) : <div />}

                  {nextPost ? (
                    <button 
                      onClick={() => switchPost(nextPost)}
                      className="group flex flex-col items-end p-6 rounded-2xl bg-slate-900/50 border border-slate-800 hover:border-indigo-500/50 transition-all text-right"
                    >
                      <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest mb-3">Next Entry</span>
                      <span className="text-white font-bold text-lg leading-tight group-hover:text-indigo-300 transition-colors">
                        {nextPost.title}
                      </span>
                    </button>
                  ) : <div />}
                </nav>
              </article>
            </main>
          </div>

          {/* Reading Progress Bar */}
          <div className="fixed top-0 left-0 w-full h-1 z-[120] pointer-events-none">
             <div 
              className="h-full bg-gradient-to-r from-indigo-500 to-cyan-400 transition-all duration-150 ease-out shadow-[0_0_10px_rgba(99,102,241,0.5)]"
              style={{ width: `${readingProgress}%` }}
             ></div>
          </div>
        </div>
      )}
    </section>
  );
};

export default BlogSection;
